name: Scrape Formula 1 Results
on:
  push:
    branches:
      - main
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas beautifulsoup4
      - name: Scrape Formula 1 Results
        run: |
          import requests
          from bs4 import BeautifulSoup
          import pandas as pd

          url = 'https://www.formula1.com/en/results.html/2023/drivers.html'
          page = requests.get(url)
          soup = BeautifulSoup(page.content, 'html.parser')
          table = soup.find_all('table')[0]
          df = pd.read_html(str(table))[0]
          print(df.to_json(orient='records'))
